name: Test Canboat json Changes

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  build_and_test:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout canboatjs
      uses: actions/checkout@v4
      with:
        path: ./canboatjs
  
    - name: Checkout canboat.json
      uses: actions/checkout@v4
      with:
        repository: canboat/canboat
        path: ./canboat
        sparse-checkout: |
          docs/canboat.json
        sparse-checkout-cone-mode: false

    - name: Checkout ts-pgns
      uses: actions/checkout@v4
      with:
        repository: canboat/ts-pgns
        path: ./ts-pgns
  
    - name: Checkout n2k-signalk
      uses: actions/checkout@v4
      with:
        repository: SignalK/n2k-signalk
        path: ./n2k-signalk

    - name: Checkout signalk-to-nmea2000
      uses: actions/checkout@v4
      with:
        repository: SignalK/signalk-to-nmea2000
        ref: typescript
        path: ./signalk-to-nmea2000
        
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        
    - name: Build & Test ts-pgns
      run: |
        cp ../canboat/docs/canboat.json .
        npm install
        npm run build
        npm run generate
        npm run build
        npm test
        npm link
      working-directory: ./ts-pgns

    - name: Build & Test canboatjs
      run: |
        npm install
        npm link @canboat/ts-pgns
        npm run build
        npm link
        npm test
      working-directory: ./canboatjs

    - name: Build & Test n2k-signalk
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
        npm test
      working-directory: ./n2k-signalk

    - name: Build & Test signalk-to-nmea2000
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
        npm test
      working-directory: ./signalk-to-nmea2000

