name: Test Canboat json Changes

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:
    inputs:
      canboat-repository:
        description: 'Repository to get canboat.json from'
        default: 'canboat/canboat'
        required: true
      canboat-branch:
        description: 'Branch to get canboat.json from'
        default: 'master'
        required: true
      canboatjs-branch:
        description: 'Branch to get canboatjs from'
        default: 'master'
        required: true
      ts-pgns-branch:
        description: 'Branch to get ts-pgns from'
        default: 'main'
        required: true        

jobs:
  build_and_test:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout canboatjs
      uses: actions/checkout@v4
      with:
        path: ./canboatjs
        ref: ${{ github.event.inputs.canboatjs-branch }}
  
    - name: Checkout canboat.json
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.canboat-repository }}
        path: ./canboat
        ref: ${{ github.event.inputs.canboat-branch }}
        sparse-checkout: |
          docs/canboat.json
        sparse-checkout-cone-mode: false

    - name: Checkout ts-pgns
      uses: actions/checkout@v4
      with:
        repository: canboat/ts-pgns
        path: ./ts-pgns
        ref: ${{ github.event.inputs.ts-pgns-branch }}
  
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        
    - name: Build & Test ts-pgns
      run: |
        cp ../canboat/docs/canboat.json .
        npm install
        npm run build
        npm run generate
        npm run build
        npm test
        npm link
      working-directory: ./ts-pgns

    - name: Build & Test canboatjs
      run: |
        npm install
        npm link @canboat/ts-pgns
        npm run build
        npm link
        npm test
      working-directory: ./canboatjs
      continue-on-error: true

    - name: Checkout n2k-signalk
      uses: actions/checkout@v4
      with:
        repository: SignalK/n2k-signalk
        path: ./n2k-signalk

    - name: Build & Test n2k-signalk
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
        npm test
      working-directory: ./n2k-signalk
      continue-on-error: true

    - name: Checkout signalk-to-nmea2000
      uses: actions/checkout@v4
      with:
        repository: SignalK/signalk-to-nmea2000
        ref: typescript
        path: ./signalk-to-nmea2000

    - name: Build & Test signalk-to-nmea2000
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
        npm test
      working-directory: ./signalk-to-nmea2000
      continue-on-error: true

    - name: Checkout signalk-n2k-switching
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2k-switching
        path: ./signalk-n2k-switching

    - name: Build signalk-n2k-switching
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-n2k-switching
      continue-on-error: true

    - name: Checkout signalk-n2k-displays
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2k-displays
        ref: ts-pgns
        path: ./signalk-n2k-displays

    - name: Build signalk-n2k-displays
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-n2k-displays
      continue-on-error: true

    - name: Checkout signalk-n2k-switching-emulator
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2k-switching-emulator
        ref: main
        path: ./signalk-n2k-switching-emulator

    - name: Build signalk-n2k-switching-emulator
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-n2k-switching-emulator
      continue-on-error: true

    - name: Checkout signalk-alarm-silencer
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-alarm-silencer
        ref: ts-pgns
        path: ./signalk-alarm-silencer

    - name: Build signalk-alarm-silencer
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-alarm-silencer
      continue-on-error: true

    - name: Checkout signalk-fusion-stereo
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-fusion-stereo
        ref: master
        path: ./signalk-fusion-stereo

    - name: Build signalk-fusion-stereo
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-fusion-stereo
      continue-on-error: true

    - name: Checkout signalk-yd-alarm-button
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-yd-alarm-button
        ref: ts-pgns
        path: ./signalk-yd-alarm-button

    - name: Build signalk-yd-alarm-button
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
      working-directory: ./signalk-yd-alarm-button
      continue-on-error: true

    - name: Checkout signalk-n2kais-to-nmea0183
      uses: actions/checkout@v4
      with:
        repository: sbender9/signalk-n2kais-to-nmea0183
        path: ./signalk-n2kais-to-nmea0183

    - name: Build signalk-n2kais-to-nmea0183
      run: |
        npm install
        npm link @canboat/canboatjs
        npm link @canboat/ts-pgns
        npm run build
        npm test
      working-directory: ./signalk-n2kais-to-nmea0183
      continue-on-error: true
